'<!DOCTYPE HTML>' + LineEnding +
'<html lang="pt-BR">' + LineEnding +
'<head>' + LineEnding +
'	<meta charset="UTF-8">' + LineEnding +
'	<title>%s</title>' + LineEnding +
'</head>' + LineEnding +
'<body>' + LineEnding +
'	<form action="/cgi-bin/cgi1.bf" method="post">' + LineEnding +
'		ID: <input type="text" name="id" /><br />' + LineEnding +
'		Nome: <input type="text" name="nome" /><br />' + LineEnding +
'		<input type="submit" />' + LineEnding +
'	</form>' + LineEnding +
'</body>' + LineEnding +
'</html>'
